auth:
  # Вид аутентификации
  #   email: по электронной почте (код через email)
  #   phone: по номеру телефона (код через смс)
  #   mixed: смешанная аутентификация (в поле auth_id может быть email или номер телефона)
  type: "email"

  # Можно ли регистрировать новых пользователей (если при получении кода окажется что такого пользователя нет он будет создан)
  can_registration_users: false

  # Количество генераций новых кодов в день
  attempts_per_day: 50

  # Время устаревания кодов аутентификации (в часах)
  auth_codes_older_than_hours: 2

  # Время устаревания сессий (в днях), сессии которыми не пользовались
  sessions_older_than_days: 30

  # Привязка сессии к IP-адресу
  sessions_binding_to_ip: false
