cron:
  # Префикс для имён заданий
  #
  # В случае, когда у вас на одном сервере несколько проектов, имена задач обязательно должны отличаться,
  # иначе это приводит к конфликтам при запуске задач
  name_prefix: "MyApp1"

  # Путь до лог-файла
  log_file: "/var/logs/cron.log"

  # Массив email-адресов, куда отправлять письма с ошибками
  errors_emails: []

  # Выполнять (true) или нет (false) cron-задачу: Очистка устаревших токенов для скачивания файлов
  file_older_tokens_enabled: true

  # Выполнять (true) или нет (false) cron-задачу: Очистка устаревших файлов во временном каталоге
  file_older_files_enabled: true

  # Выполнять (true) или нет (false) cron-задачу: Ротация таблицы data_change_logs
  data_change_logs_rotator_enabled: true
