file:
  # Каталог для логов (полный путь, без конечной "/")
  path_logs: "/path/to/project/var/logs"

  # Путь до временного хранилища (полный путь, без конечной "/")
  path_temp: "/path/to/project/var/temp"

  # Путь до постоянного хранилища (полный путь, без конечной "/")
  path_upload: "/path/to/project/var/documents"

  # Полное удаление файлов
  #   true - файл удаляется физически, а также удаляется запись в БД
  #   false - файл физически не удаляется, а в БД помечается как удалённый
  full_remove: false

  # Через сколько дней временный файл считать устаревшим
  outdated_file_days: 5

  # Через сколько часов токен на скачивание файла считать устаревшим
  tokens_older_than_hours: 12

  # Максимальный размер загружаемого файла (в байтах)
  allowed_size_bytes: 2097152 # 2 MB

  # Формат сообщения о превышении лимита размера загружаемого файла
  allowed_size_formated: "2 MB"

  # Режим проверки файла: по типу содержимого (type) или по расширению (ext)
  check_file_by: "type"

  # Массив разрешенных типов
  allowed_types:
    - "application/pdf" # pdf
    - "application/msword" # doc
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document" # docx
    - "application/vnd.ms-excel" # xls
    - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" # xlsx
    - "application/zip" # zip
    - "application/x-rar" # rar

  # Массив разрешенных расширений
  allowed_extensions: ["pdf", "doc", "docx", "xls", "xlsx", "zip", "rar"]
