general:
  # Вид сервера: разработчика
  const_server_type_dev: &dev "dev"

  # Вид сервера: тестовый
  const_server_type_test: "test"

  # Вид сервера: боевой
  const_server_type_prod: "prod"

  # Имя проекта
  app_name: "Lemurro"

  # Вид сервера
  server_type: *dev
