# Список разрешённых заголовков
headers:
  - "X-SESSION-ID" # Идентификатор сессии
  - "X-UTC-OFFSET" # Смещение временной зоны пользователя относительно UTC
  - "X-Requested-With" # Необходим для CORS
  - "X-File-Name" # Необходим для загрузки файлов
