maintenance:
  # Включить \ Выключить обслуживание проекта
  active: false

  # Сообщение об обслуживании
  message: "Проект временно остановлен на обслуживание, пожалуйста повторите свой запрос через 5 минут или обновите страницу"
