name: API tests

on:
  push:
    branches: [ master, v1.10 ]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        include:
          - lemurro_version: "1.10"
            sql_file: "database.sql"
            php_version: "7.4"
            operating-system: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set environment variables"
        run: |
          echo "PROJ_FOLDER=$GITHUB_WORKSPACE/testproject" >> $GITHUB_ENV
          echo "CONFIGS_FOLDER=$GITHUB_WORKSPACE/testproject/api/app/Configs" >> $GITHUB_ENV
          echo "APP_TESTS_FOLDER=$GITHUB_WORKSPACE/testproject/api/tests" >> $GITHUB_ENV
          echo "CORE_TESTS_FOLDER=$GITHUB_WORKSPACE/testproject/api/vendor/lemurro/api-core/tests" >> $GITHUB_ENV

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: "Versions"
        run: |
          lsb_release -a
          mysql -V
          php -v

      - name: "Install Lemurro"
        run: |
          composer global require --no-progress --no-scripts --no-plugins lemurro/installer
          sed -i 's/setTty(true)/setTty(false)/g' ~/.composer/vendor/lemurro/installer/src/NewCommand.php
          ~/.composer/vendor/bin/lemurro new testproject --lv=${{ matrix.lemurro_version }} --api --skip --silent
          composer install --working-dir=$PROJ_FOLDER/api/vendor/lemurro/api-core

      - name: "Prepare database"
        run: |
          touch ~/.my.cnf
          echo -e "[mysql]\nuser=root\npassword=root\n" > ~/.my.cnf
          mysql -h 127.0.0.1 --execute="CREATE DATABASE lemurro CHARACTER SET utf8mb4;"
          mysql -h 127.0.0.1 lemurro < $PROJ_FOLDER/api/${{ matrix.sql_file }}
          mysql -h 127.0.0.1 --execute="SELECT * FROM lemurro.users;"

      - name: "Configuration application"
        run: |
          cp $CONFIGS_FOLDER/SettingsAuth.example.php $CONFIGS_FOLDER/SettingsAuth.php
          cp $CONFIGS_FOLDER/SettingsCron.example.php $CONFIGS_FOLDER/SettingsCron.php
          cp $CONFIGS_FOLDER/SettingsDatabase.example.php $CONFIGS_FOLDER/SettingsDatabase.php
          cp $CONFIGS_FOLDER/SettingsFile.example.php $CONFIGS_FOLDER/SettingsFile.php
          cp $CONFIGS_FOLDER/SettingsGeneral.example.php $CONFIGS_FOLDER/SettingsGeneral.php
          cp $CONFIGS_FOLDER/SettingsMail.example.php $CONFIGS_FOLDER/SettingsMail.php
          cp $CONFIGS_FOLDER/SettingsMaintenance.example.php $CONFIGS_FOLDER/SettingsMaintenance.php
          cp $CONFIGS_FOLDER/SettingsPath.example.php $CONFIGS_FOLDER/SettingsPath.php
          cp $CONFIGS_FOLDER/SettingsSMS.example.php $CONFIGS_FOLDER/SettingsSMS.php
          sed -i "s/PASSWORD = ''/PASSWORD = 'root'/g" $CONFIGS_FOLDER/SettingsDatabase.php

      - name: "Configuration application tests"
        run: |
          cp $APP_TESTS_FOLDER/api.suite.dist.yml $APP_TESTS_FOLDER/api.suite.yml
          sed -i 's/password: ""/password: "root"/g' $APP_TESTS_FOLDER/api.suite.yml
          cat $APP_TESTS_FOLDER/api.suite.yml

      - name: "Configuration core tests"
        run: |
          cp $CORE_TESTS_FOLDER/api.suite.dist.yml $CORE_TESTS_FOLDER/api.suite.yml
          sed -i 's/password: ""/password: "root"/g' $CORE_TESTS_FOLDER/api.suite.yml
          cat $CORE_TESTS_FOLDER/api.suite.yml

      - name: "Running web server"
        run: |
          cp /etc/php/${{ matrix.php_version }}/cli/php.ini $GITHUB_WORKSPACE/php.ini
          sed -i 's/log_errors = Off/log_errors = On/g' $GITHUB_WORKSPACE/php.ini
          sed -i "s|;error_log = php_errors.log|error_log = $GITHUB_WORKSPACE/php_errors.log|g" $GITHUB_WORKSPACE/php.ini
          php -S localhost:8000 -t $PROJ_FOLDER/api/public -c $GITHUB_WORKSPACE/php.ini &

      - name: "Running core tests"
        run: |
          cd $PROJ_FOLDER/api/vendor/lemurro/api-core
          php vendor/bin/codecept run api

      - name: "Running application tests"
        run: |
          cd $PROJ_FOLDER/api
          php vendor/bin/codecept run api

      - name: "Debug"
        if: failure()
        run: |
          cat $GITHUB_WORKSPACE/php_errors.log